
--ALTER TABLE `Allocation` CHANGE `DNRecvDate` `DNRecvDate` DATE NULL DEFAULT NULL, CHANGE `MSPaidDateI` `MSPaidDateI` DATE NULL DEFAULT NULL, CHANGE `MSPaidDateII` `MSPaidDateII` DATE NULL DEFAULT NULL, CHANGE `SIBSS1PaidDate` `SIBSS1PaidDate` DATE NULL DEFAULT NULL, CHANGE `SIBSS2PaidDate` `SIBSS2PaidDate` DATE NULL DEFAULT NULL, CHANGE `SIBSS3Staff1PaidDate` `SIBSS3Staff1PaidDate` DATE NULL DEFAULT NULL, CHANGE `SIBSS3Staff2PaidDate` `SIBSS3Staff2PaidDate` DATE NULL DEFAULT NULL, CHANGE `SIBSS4PaidDate` `SIBSS4PaidDate` DATE NULL DEFAULT NULL, CHANGE `SIBSS5PaidDate` `SIBSS5PaidDate` DATE NULL DEFAULT NULL;

--ALTER TABLE `ClientMtn` CHANGE `DateOfIncorp` `DateOfIncorp` DATE NULL DEFAULT NULL, CHANGE `NormalYearEndDate` `NormalYearEndDate` DATE NOT NULL, CHANGE `NonTaxDeadlineDate` `NonTaxDeadlineDate` DATE NULL DEFAULT NULL, CHANGE `LastClientStatusDate` `LastClientStatusDate` DATE NULL DEFAULT NULL;

--ALTER TABLE `JobMtn` CHANGE `RecordDate` `RecordDate` DATE NULL DEFAULT NULL, CHANGE `JobPeriodFrom` `JobPeriodFrom` DATE NULL DEFAULT NULL, CHANGE `JobPeriodTo` `JobPeriodTo` DATE NOT NULL, CHANGE `OfficialDeadline` `OfficialDeadline` DATE NOT NULL, CHANGE `QuotationSentDate` `QuotationSentDate` DATE NULL DEFAULT NULL, CHANGE `QuotationConfirmedDate` `QuotationConfirmedDate` DATE NULL DEFAULT NULL, CHANGE `WorkingDeadline` `WorkingDeadline` DATE NOT NULL, CHANGE `JobDeadline` `JobDeadline` DATE NOT NULL;

--ALTER TABLE `JobProg` CHANGE `S1DCDocRequestDate` `S1DCDocRequestDate` DATE NULL DEFAULT NULL, CHANGE `S1DCDocReceivedToHKO1stDate` `S1DCDocReceivedToHKO1stDate` DATE NULL DEFAULT NULL, CHANGE `S1DCDocReceivedToHKO2ndDate` `S1DCDocReceivedToHKO2ndDate` DATE NULL DEFAULT NULL, CHANGE `S1DCDocReceivedLastdate80` `S1DCDocReceivedLastdate80` DATE NULL DEFAULT NULL, CHANGE `S2DDDocTsfArrivalDate` `S2DDDocTsfArrivalDate` DATE NULL DEFAULT NULL, CHANGE `S2DDBreifingDate` `S2DDBreifingDate` DATE NULL DEFAULT NULL, CHANGE `S3ACCommenceDate` `S3ACCommenceDate` DATE NULL DEFAULT NULL, CHANGE `S3ACInfoOutstanding1st` `S3ACInfoOutstanding1st` DATE NULL DEFAULT NULL, CHANGE `S3ACInfoOutstanding1stReply` `S3ACInfoOutstanding1stReply` DATE NULL DEFAULT NULL, CHANGE `S3ACInfoOutstanding2nd` `S3ACInfoOutstanding2nd` DATE NULL DEFAULT NULL, CHANGE `S3ACInfoOutstanding2ndReply` `S3ACInfoOutstanding2ndReply` DATE NULL DEFAULT NULL, CHANGE `S3ACDraftFSDate` `S3ACDraftFSDate` DATE NULL DEFAULT NULL, CHANGE `S4FSR1stReviewDate` `S4FSR1stReviewDate` DATE NULL DEFAULT NULL, CHANGE `S4FSR1stReviewAmendedDate` `S4FSR1stReviewAmendedDate` DATE NULL DEFAULT NULL, CHANGE `S4FSR2ndReviewDate` `S4FSR2ndReviewDate` DATE NULL DEFAULT NULL, CHANGE `S4FSR2ndReviewAmendedDate` `S4FSR2ndReviewAmendedDate` DATE NULL DEFAULT NULL, CHANGE `S5FSFChecklistSignoffDate` `S5FSFChecklistSignoffDate` DATE NULL DEFAULT NULL, CHANGE `S5FSFFSPrintedDate` `S5FSFFSPrintedDate` DATE NULL DEFAULT NULL, CHANGE `S5FSFDNDatexx` `S5FSFDNDatexx` DATE NULL DEFAULT NULL, CHANGE `S5FSFFSPackeSentDate` `S5FSFFSPackeSentDate` DATE NULL DEFAULT NULL, CHANGE `S6DFFiledDate` `S6DFFiledDate` DATE NULL DEFAULT NULL, CHANGE `SRDRHKODate` `SRDRHKODate` DATE NULL DEFAULT NULL, CHANGE `SRDRDocDespatchedInviteDate` `SRDRDocDespatchedInviteDate` DATE NULL DEFAULT NULL, CHANGE `SRDRDocDespatchedDeliveryDate` `SRDRDocDespatchedDeliveryDate` DATE NULL DEFAULT NULL;

-- CREATE TABLE `allocationparam`  (
--   `ID` int(10) NOT NULL AUTO_INCREMENT,
--   `FieldName` varchar(255) not NULL,
--   `FieldValue` varchar(255) not NULL,
--   PRIMARY KEY (`ID`)
-- ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci;
-- INSERT INTO `allocationparam` (`ID`, `FieldName`, `FieldValue`) VALUES
-- (1, 'SIBSOverallPct', ''),
-- (2, 'SIBSS1SetPct', ''),
-- (3, 'SIBSS2SetPct', ''),
-- (4, 'SIBSS3SetPct', ''),
-- (5, 'SIBSS4SetPct', ''),
-- (6, 'SIBSS5SetPct', '');
-- 
-- 
-- CREATE TABLE `allocationhistory`  (
--   `ID` int(10) NOT NULL AUTO_INCREMENT,
--   `FieldName` varchar(255) not NULL,
--   `FieldValue` varchar(255) not NULL,
--   `ModifyDate` datetime not NULL,
--   PRIMARY KEY (`ID`)
-- ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci;

DROP TABLE IF EXISTS `job`;
CREATE TABLE `job`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `JobCode` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,

  `RecordDate` date DEFAULT NULL,
  `ClientCode1` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `JobNature` varchar(7) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `JobPeriodFrom` date DEFAULT NULL,
  `JobPeriodTo` date NOT NULL,
  `OfficialDeadline` date NOT NULL,
  `JobNo` int(11) NOT NULL DEFAULT 0,
  `QuotationVia` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `QuotationSentDate` date DEFAULT NULL,
  `QuotationProposedFee` decimal(19, 4) DEFAULT NULL,
  `QuotationConfirmedDate` date DEFAULT NULL,
  `QuotationAgreedFee` decimal(19, 4) NOT NULL,
  `WorkingDeadline` date NOT NULL,
  `JobDeadline` date NOT NULL,

  `S1DCDocRequestVia` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S1DCDocRequestDate` date DEFAULT NULL,
  `S1DCDocReceivedToHKO1stDate` date DEFAULT NULL,
  `S1DCDocReceivedToHKO2ndDate` date DEFAULT NULL,
  `S1DCDocReceivedLastdate80` date DEFAULT NULL,
  `S1DCDocReceivedToHKOContent` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S1DCStaff` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S1DCok` tinyint(1) DEFAULT 0,
  `S2DDOfficeHandled` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S2DDDocTsfvia` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S2DDDocTsfArrivalDate` date DEFAULT NULL,
  `S2DDBreifingDate` date DEFAULT NULL,
  `S2DDStaff` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S2DDok` tinyint(1) DEFAULT 0,
  `S3ACCommenceDate` date DEFAULT NULL,
  `S3ACStaff1` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S3ACStaff2` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S3ACInfoOutstanding1st` date DEFAULT NULL,
  `S3ACInfoOutstanding1stReply` date DEFAULT NULL,
  `S3ACInfoOutstanding2nd` date DEFAULT NULL,
  `S3ACInfoOutstanding2ndReply` date DEFAULT NULL,
  `S3ACStaff3` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S3ACDraftFSDate` date DEFAULT NULL,
  `S3ACStaff4` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S3ACok` tinyint(1) DEFAULT 0,
  `S4FSR1stReviewDate` date DEFAULT NULL,
  `S4FSR1stReviewAmendedDate` date DEFAULT NULL,
  `S4FSR2ndReviewDate` date DEFAULT NULL,
  `S4FSR2ndReviewAmendedDate` date DEFAULT NULL,
  `S4FSRStaff` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S4FSRok` tinyint(1) DEFAULT 0,
  `S5FSFChecklistSignoffBy` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S5FSFChecklistSignoffDate` date DEFAULT NULL,
  `S5FSFFSPrintedBy` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S5FSFFSPrintedDate` date DEFAULT NULL,
  `S5FSFDNIssuedBy` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S5FSFDNNoxx` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S5FSFDNDatexx` date DEFAULT NULL,
  `S5FSFDNAmountxx` decimal(19, 4) DEFAULT NULL,
  `S5FSFFSPackeSentBy` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S5FSFFSPackeSentDate` date DEFAULT NULL,
  `S5FSFNoOfQFrClient` int(11) DEFAULT NULL,
  `S5FSFok` tinyint(1) DEFAULT 0,
  `S6DFPackedUpClientDoc` tinyint(1) DEFAULT 0,
  `S6DFPackedUpSoftcopy` tinyint(1) DEFAULT 0,
  `S6DFPackedUpHardcopy` tinyint(1) DEFAULT 0,
  `S6DFFiledDoc` tinyint(1) DEFAULT 0,
  `S6DFFiledDate` date DEFAULT NULL,
  `S6DFFiledStaff` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S6DFDocLoc` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `S6DFok` tinyint(1) DEFAULT 0,
  `SRDRHKODate` date DEFAULT NULL,
  `SRDRStoreLoc` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `SRDRDocDespatchedTo` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `SRDRDocDespatchedInviteDate` date DEFAULT NULL,
  `SRDRDocDespatchedDeliveryDate` date DEFAULT NULL,
  `SRDRDocDespatchedDeliveryStaff` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `SRDRok` tinyint(1) DEFAULT 0,
  `Remarks1` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `Remarks2` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,

  `Done` tinyint(1) DEFAULT 0,
  `DNRecvDate` date DEFAULT NULL,
  `Paid` tinyint(1) DEFAULT 0,
  `MSPctI` double DEFAULT 0,
  `MSEntitledAmount1` decimal(19, 4) DEFAULT NULL,
  `MSPaidDateI` date DEFAULT NULL,
  `MSPctII` double DEFAULT 0,
  `MSAcMgrII` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `MSEntitledAmount2` decimal(19, 4) DEFAULT NULL,
  `MSPaidDateII` date DEFAULT NULL,
  `SIBSOverallPct` double DEFAULT 0,
  `SIBSS1SetPct` double DEFAULT 0,
  `SIBSS1AdjPct` double DEFAULT 0,
  `SIBSS1CSFtr` double DEFAULT 0,
  `SIBSS1EntitledAmount` decimal(19, 4) DEFAULT NULL,
  `SIBSS1PaidDate` date DEFAULT NULL,
  `SIBSS2SetPct` double DEFAULT 0,
  `SIBSS2AdjPct` double DEFAULT 0,
  `SIBSS2CSFtr` double DEFAULT 0,
  `SIBSS2EntitledAmount` decimal(19, 4) DEFAULT NULL,
  `SIBSS2PaidDate` date DEFAULT NULL,
  `SIBSS3SetPct` double DEFAULT 0,
  `SIBSS3CSFtr` double DEFAULT 0,
  `SIBSS3Staff1Pct` double DEFAULT 0,
  `SIBSS3Staff1EntitledAmount` decimal(19, 4) DEFAULT NULL,
  `SIBSS3Staff1PaidDate` date DEFAULT NULL,
  `SIBSS3Staff2Pct` double DEFAULT 0,
  `SIBSS3Staff2EntitledAmount` decimal(19, 4) DEFAULT NULL,
  `SIBSS3Staff2PaidDate` date DEFAULT NULL,
  `SIBSS4SetPct` double DEFAULT 0,
  `SIBSS4AdjPct` double DEFAULT 0,
  `SIBSS4CSFtr` double DEFAULT 0,
  `SIBSS4EntitledAmount` decimal(19, 4) DEFAULT NULL,
  `SIBSS4PaidDate` date DEFAULT NULL,
  `SIBSS5SetPct` double DEFAULT 0,
  `SIBSS5AdjPct` double DEFAULT 0,
  `SIBSS5CSFtr` double DEFAULT 0,
  `SIBSS5EntitledAmount` decimal(19, 4) DEFAULT NULL,
  `SIBSS5PaidDate` date DEFAULT NULL,
  `MSSIBSRemarks` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `JobCode`(`JobCode`)
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;
